model_id: Qwen/Qwen2.5-7B-Instruct
model_family: qwen2.5

LoRA:
  r: 0
  alpha: 128
  dropout: 0.05

used_policy: True
used_strategy: True
step_token: <step>,</step>
answer_token: <answer>,</answer>

loss_type: grad_ascent
tune_vision_tower: False
tune_mm_projector: True
tune_language_model: True
data_path: ./dataset/safety_reasoning_v3_3step.json
split: with_strategy_policy_3step
batch_size: 2
gradient_accumulation_steps: 16
max_grad_norm: 1.0
num_epochs: 2
max_length: 3072
save_dir: models/final_ft_${num_epochs}_epochs_lr${lr}_${model_family}_${split}
save_steps: 177
lr: 1e-5
weight_decay: 0.01
seed: 233
workers: 4
lr_scheduler_type: "cosine"
warmup_ratio: 0.00
max_train_steps: -1
report_to: "wandb"
resume_from_checkpoint: ""
