seed: 233
iter: 20
seed_prompts_file: data/AdvBench/advBench.json
task_name: KaggleChallenge
output_path: ./data/raw_data/${task_name}/rollout${num_rollouts}
reward_url: gpt

# LLM Config
model_ckpt: openai/gpt-oss-20b
dtype: "half"

# SamplingParams
temperature: 0.7
top_p: 0.8
top_k: 20
max_new_tokens: 4096
do_sample: True
half_precision: True

# Worker Config
worker_num: 1
worker_prompt_num: 100000
use_policy: True 
use_strategy: True
start_idx: 0
end_idx: 100000000
stop_token_ids: [200002]


num_rollouts: 2
exploration_weight: 1.5
max_depth: 5
generate_samples_number: [3, 4, 3, 2, 4, 3, 3, 3]
# generate_samples_number: [1, 1, 1, 1, 1, 1, 1, 1]
# visit_all_node: True
p_average_strategy: "uniform"
able_to_reselected: True
score_type: "UCB"
show_tree_file: ${output_path}/all-steps