# LLM Config
seed: 233
model_name: Qwen/Qwen3-14B
attack_model_ckpt: Qwen/Qwen3-14B
dtype: "half"
tensor_parallel_size: 1
max_num_seqs: 10
swap_space: 4
gpu_memory_utilization: 0.95
max_model_len: 15000
api: vllm

# SamplingParams
temperature: 0.7
top_p: 0.8
top_k: 20
max_tokens: 8192
repetition_penalty: 1.0
half_precision: True