# model
model_name_or_path: "Qwen/Qwen3-8B"

# data
data_path: "data/processed/Qwen8B-wildjailbreak-llama-8B"

# training
cache_dir: null
optim: "adamw_torch"
model_max_length: 3074
deepspeed: "config/ds_config.json"
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
model_max_length: 15000
overwrite_output_dir: true
bf16: true

output_dir: "./checkpoints/1"
num_train_epochs: 1
save_strategy: "steps" 
save_steps: 500
save_total_limit: 5 
evaluation_strategy: "no" 
logging_steps: 50
logging_dir: "./logs"
report_to: "tensorboard"  

learning_rate: 1e-5